In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\flight-delay-intelligence\\data\\raw\\flights_data.csv")

In [3]:
df.head(5)

,Used Date,From,To,Airline,Scheduled Departure,SDEP,Departure,DEP,Scheduled Arrival,SARR,...,Market Share,OTP Index,weather__hourly__windspeedKmph,weather__hourly__weatherDesc__value,weather__hourly__precipMM,weather__hourly__humidity,weather__hourly__visibility,weather__hourly__pressure,weather__hourly__cloudcover,Category
0,31-01-2020,DEL,HYD,Air Asia,6:05,605,6:04,604,8:15,815,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,0
1,31-01-2020,DEL,HYD,Indigo,4:50,450,4:36,436,7:00,700,...,47.5,81.1,11,Partly cloudy,0,90,9,1012,57,0
2,30-01-2020,DEL,HYD,Air Asia,6:05,605,5:54,554,8:15,815,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,0
3,30-01-2020,DEL,HYD,Air Asia,17:40,1740,17:40,1740,19:55,1955,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,0
4,30-01-2020,DEL,HYD,Air Asia,19:50,1950,19:54,1954,22:10,2210,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,1

In [5]:
df.shape

(10718, 29)

In [6]:
df.columns

Index(['Used Date', 'From', 'To', 'Airline', 'Scheduled Departure', 'SDEP',
       'Departure', 'DEP', 'Scheduled Arrival', 'SARR', 'Arrival', 'ARR',
       'Departure Delay', 'Arrival Delay', 'Status', 'Distance',
       'Passenger Load Factor', 'Airline Rating', 'Airport Rating',
       'Market Share', 'OTP Index', 'weather__hourly__windspeedKmph',
       'weather__hourly__weatherDesc__value', 'weather__hourly__precipMM',
       'weather__hourly__humidity', 'weather__hourly__visibility',
       'weather__hourly__pressure', 'weather__hourly__cloudcover', 'Category'],
      dtype='object')

In [7]:
df.info

<bound method DataFrame.info of         Used Date From   To   Airline Scheduled Departure  SDEP Departure  \
0      31-01-2020  DEL  HYD  Air Asia                6:05   605      6:04
1      31-01-2020  DEL  HYD    Indigo                4:50   450      4:36
2      30-01-2020  DEL  HYD  Air Asia                6:05   605      5:54
3      30-01-2020  DEL  HYD  Air Asia               17:40  1740     17:40
4      30-01-2020  DEL  HYD  Air Asia               19:50  1950     19:54
...           ...  ...  ...       ...                 ...   ...       ...
10713  24-01-2019  CCU  DEL  SpiceJet               18:30  1830     18:30
10714  23-01-2019  CCU  DEL  SpiceJet               18:30  1830     18:30
10715  22-01-2019  CCU  DEL  SpiceJet               18:30  1830     18:38
10716    9/1/2019  DEL  HYD  Spicejet               22:05  2205      0:40
10717    2/1/2019  BOM  DEL   Vistara                1:10   110       130

        DEP Scheduled Arrival  SARR  ... Market Share  OTP Index  \
0       604              8:15   815  ...          5.3       85.6
1       436              7:00   700  ...         47.5       81.1
2       554              8:15   815  ...          5.3       85.6
3      1740             19:55  1955  ...          5.3       85.6
4      1954             22:10  2210  ...          5.3       85.6
...     ...               ...   ...  ...          ...        ...
10713  1830             20:55  2055  ...         13.3       69.2
10714  1830             20:55  2055  ...         13.3       69.2
10715  1838             20:55  2055  ...         13.3       69.2
10716    40              0:25    25  ...         13.3       69.2
10717   130              3:20   320  ...          3.8       76.2

       weather__hourly__windspeedKmph  weather__hourly__weatherDesc__value  \
0                                  11                        Partly cloudy
1                                  11                        Partly cloudy
2                                  11                        Partly cloudy
3                                  11                        Partly cloudy
4                                  11                        Partly cloudy
...                               ...                                  ...
10713                               6                                Clear
10714                               3                                Clear
10715                               5                                Clear
10716                               8                 Patchy rain possible
10717                               8                                Clear

       weather__hourly__precipMM  weather__hourly__humidity  \
0                              0                         90
1                              0                         90
2                              0                         90
3                              0                         90
4                              0                         90
...                          ...                        ...
10713                          0                         29
10714                          0                         27
10715                          0                         28
10716                          1                         55
10717                          0                         47

       weather__hourly__visibility  weather__hourly__pressure  \
0                                9                       1012
1                                9                       1012
2                                9                       1012
3                                9                       1012
4                                9                       1012
...                            ...                        ...
10713                           10                       1016
10714                           10                       1015
10715                           10                       1015
10716                            9                        997
10717                           10                       1018

       weather__hourly__cloudcover  Category
0                               57         0
1                               57         0
2                               57         0
3                               57         0
4                               57         1
...                            ...       ...
10713                            1         0
10714                            0         0
10715                            0         1
10716                           85         4
10717                            0         2

[10718 rows x 29 columns]>

In [8]:
df.describe()

,SDEP,DEP,SARR,ARR,Departure Delay,Arrival Delay,Status,Distance,Passenger Load Factor,Airline Rating,Airport Rating,Market Share,OTP Index,weather__hourly__windspeedKmph,weather__hourly__precipMM,weather__hourly__humidity,weather__hourly__visibility,weather__hourly__pressure,weather__hourly__cloudcover,Category
count,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000
mean,1347.070349,1331.483486,1320.709461,1260.562605,26.080892,27.628009,0.992909,1287.418175,86.294365,0.588813,0.887912,24.202351,79.493180,12.323195,0.241090,62.952323,9.953443,1012.578000,32.011569,1.031069
std,642.298422,666.186884,704.680126,723.536840,126.088783,133.545628,0.083912,319.679362,3.779119,0.157973,0.016148,18.409805,7.158847,5.428185,1.078129,21.806752,1.715943,4.404972,28.207542,1.323295
min,5.000000,-1.000000,5.000000,-1.000000,-60.000000,-61.000000,0.000000,848.000000,76.000000,0.300000,0.860000,3.800000,53.100000,1.000000,0.000000,5.000000,2.000000,991.000000,0.000000,0.000000
25%,730.000000,726.000000,835.000000,754.250000,0.000000,-4.000000,1.000000,1138.000000,84.300000,0.500000,0.880000,7.000000,76.800000,9.000000,0.000000,46.000000,10.000000,1012.000000,4.000000,0.000000
50%,1320.000000,1259.000000,1245.000000,1220.000000,0.000000,3.000000,1.000000,1244.000000,85.000000,0.700000,0.900000,12.100000,81.100000,12.000000,0.000000,65.000000,10.000000,1013.000000,25.000000,0.000000
75%,2000.000000,2000.000000,2010.000000,1955.000000,19.000000,25.000000,1.000000,1736.000000,90.100000,0.700000,0.900000,47.500000,82.900000,15.000000,0.000000,83.000000,10.000000,1015.000000,57.000000,2.000000
max,2350.000000,2359.000000,2355.000000,2359.000000,1440.000000,1440.000000,1.000000,1736.000000,94.000000,0.800000,0.900000,49.900000,95.200000,36.000000,21.000000,96.000000,20.000000,1022.000000,100.000000,4.000000

In [10]:
df.isnull().sum()

Used Date                              0
From                                   0
To                                     0
Airline                                0
Scheduled Departure                    0
SDEP                                   0
Departure                              0
DEP                                    0
Scheduled Arrival                      0
SARR                                   0
Arrival                                0
ARR                                    0
Departure Delay                        0
Arrival Delay                          0
Status                                 0
Distance                               0
Passenger Load Factor                  0
Airline Rating                         0
Airport Rating                         0
Market Share                           0
OTP Index                              0
weather__hourly__windspeedKmph         0
weather__hourly__weatherDesc__value    0
weather__hourly__precipMM              0
weather__hourly__humidity              0
weather__hourly__visibility            0
weather__hourly__pressure              0
weather__hourly__cloudcover            0
Category                               0
dtype: int64

In [12]:
(df==-1).sum()

Used Date                                0
From                                     0
To                                       0
Airline                                  0
Scheduled Departure                      0
SDEP                                     0
Departure                                0
DEP                                     76
Scheduled Arrival                        0
SARR                                     0
Arrival                                  0
ARR                                     76
Departure Delay                        326
Arrival Delay                          206
Status                                   0
Distance                                 0
Passenger Load Factor                    0
Airline Rating                           0
Airport Rating                           0
Market Share                             0
OTP Index                                0
weather__hourly__windspeedKmph           0
weather__hourly__weatherDesc__value      0
weather__hourly__precipMM                0
weather__hourly__humidity                0
weather__hourly__visibility              0
weather__hourly__pressure                0
weather__hourly__cloudcover              0
Category                                 0
dtype: int64

In [13]:
df.replace(-1, np.nan, inplace=True)

In [14]:
(df==-1).sum()

Used Date                              0
From                                   0
To                                     0
Airline                                0
Scheduled Departure                    0
SDEP                                   0
Departure                              0
DEP                                    0
Scheduled Arrival                      0
SARR                                   0
Arrival                                0
ARR                                    0
Departure Delay                        0
Arrival Delay                          0
Status                                 0
Distance                               0
Passenger Load Factor                  0
Airline Rating                         0
Airport Rating                         0
Market Share                           0
OTP Index                              0
weather__hourly__windspeedKmph         0
weather__hourly__weatherDesc__value    0
weather__hourly__precipMM              0
weather__hourly__humidity              0
weather__hourly__visibility            0
weather__hourly__pressure              0
weather__hourly__cloudcover            0
Category                               0
dtype: int64

In [15]:
df.describe()

,SDEP,DEP,SARR,ARR,Departure Delay,Arrival Delay,Status,Distance,Passenger Load Factor,Airline Rating,Airport Rating,Market Share,OTP Index,weather__hourly__windspeedKmph,weather__hourly__precipMM,weather__hourly__humidity,weather__hourly__visibility,weather__hourly__pressure,weather__hourly__cloudcover,Category
count,10718.000000,10642.000000,10718.000000,10642.000000,10392.000000,10512.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000,10718.000000
mean,1347.070349,1340.999436,1320.709461,1269.572073,26.930427,28.189022,0.992909,1287.418175,86.294365,0.588813,0.887912,24.202351,79.493180,12.323195,0.241090,62.952323,9.953443,1012.578000,32.011569,1.031069
std,642.298422,658.940894,704.680126,718.189584,127.958727,134.787189,0.083912,319.679362,3.779119,0.157973,0.016148,18.409805,7.158847,5.428185,1.078129,21.806752,1.715943,4.404972,28.207542,1.323295
min,5.000000,0.000000,5.000000,0.000000,-60.000000,-61.000000,0.000000,848.000000,76.000000,0.300000,0.860000,3.800000,53.100000,1.000000,0.000000,5.000000,2.000000,991.000000,0.000000,0.000000
25%,730.000000,730.000000,835.000000,801.000000,0.000000,-4.000000,1.000000,1138.000000,84.300000,0.500000,0.880000,7.000000,76.800000,9.000000,0.000000,46.000000,10.000000,1012.000000,4.000000,0.000000
50%,1320.000000,1304.000000,1245.000000,1224.000000,1.000000,4.000000,1.000000,1244.000000,85.000000,0.700000,0.900000,12.100000,81.100000,12.000000,0.000000,65.000000,10.000000,1013.000000,25.000000,0.000000
75%,2000.000000,2001.000000,2010.000000,1955.000000,20.000000,25.000000,1.000000,1736.000000,90.100000,0.700000,0.900000,47.500000,82.900000,15.000000,0.000000,83.000000,10.000000,1015.000000,57.000000,2.000000
max,2350.000000,2359.000000,2355.000000,2359.000000,1440.000000,1440.000000,1.000000,1736.000000,94.000000,0.800000,0.900000,49.900000,95.200000,36.000000,21.000000,96.000000,20.000000,1022.000000,100.000000,4.000000

In [16]:
df[['Departure Delay', 'Arrival Delay']].describe()

       Departure Delay  Arrival Delay
count     10392.000000   10512.000000
mean         26.930427      28.189022
std         127.958727     134.787189
min         -60.000000     -61.000000
25%           0.000000      -4.000000
50%           1.000000       4.000000
75%          20.000000      25.000000
max        1440.000000    1440.000000

In [17]:
df.isnull().sum()

Used Date                                0
From                                     0
To                                       0
Airline                                  0
Scheduled Departure                      0
SDEP                                     0
Departure                                0
DEP                                     76
Scheduled Arrival                        0
SARR                                     0
Arrival                                  0
ARR                                     76
Departure Delay                        326
Arrival Delay                          206
Status                                   0
Distance                                 0
Passenger Load Factor                    0
Airline Rating                           0
Airport Rating                           0
Market Share                             0
OTP Index                                0
weather__hourly__windspeedKmph           0
weather__hourly__weatherDesc__value      0
weather__hourly__precipMM                0
weather__hourly__humidity                0
weather__hourly__visibility              0
weather__hourly__pressure                0
weather__hourly__cloudcover              0
Category                                 0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(10)

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.dtypes

Used Date                               object
From                                    object
To                                      object
Airline                                 object
Scheduled Departure                     object
SDEP                                     int64
Departure                               object
DEP                                    float64
Scheduled Arrival                       object
SARR                                     int64
Arrival                                 object
ARR                                    float64
Departure Delay                        float64
Arrival Delay                          float64
Status                                   int64
Distance                                 int64
Passenger Load Factor                  float64
Airline Rating                         float64
Airport Rating                         float64
Market Share                           float64
OTP Index                              float64
weather__hourly__windspeedKmph           int64
weather__hourly__weatherDesc__value     object
weather__hourly__precipMM                int64
weather__hourly__humidity                int64
weather__hourly__visibility              int64
weather__hourly__pressure                int64
weather__hourly__cloudcover              int64
Category                                 int64
dtype: object

In [25]:
df['Used Date'] = pd.to_datetime(df['Used Date'], format='mixed')

In [26]:
df['Used Date'].head()

0   2020-01-31
1   2020-01-31
2   2020-01-30
3   2020-01-30
4   2020-01-30
Name: Used Date, dtype: datetime64[ns]

In [27]:
numeric_cols = [
    'Departure Delay',
    'Arrival Delay',
    'Distance',
    'Passenger Load Factor',
    'Airline Rating',
    'Airport Rating',
    'Market Share',
    'OTP Index',
    'weather__hourly__windspeedKmph',
    'weather__hourly__precipMM',
    'weather__hourly__humidity',
    'weather__hourly__visibility',
    'weather__hourly__pressure',
    'weather__hourly__cloudcover'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [28]:
df.dtypes

Used Date                              datetime64[ns]
From                                           object
To                                             object
Airline                                        object
Scheduled Departure                            object
SDEP                                            int64
Departure                                      object
DEP                                           float64
Scheduled Arrival                              object
SARR                                            int64
Arrival                                        object
ARR                                           float64
Departure Delay                               float64
Arrival Delay                                 float64
Status                                          int64
Distance                                        int64
Passenger Load Factor                         float64
Airline Rating                                float64
Airport Rating                                float64
Market Share                                  float64
OTP Index                                     float64
weather__hourly__windspeedKmph                  int64
weather__hourly__weatherDesc__value            object
weather__hourly__precipMM                       int64
weather__hourly__humidity                       int64
weather__hourly__visibility                     int64
weather__hourly__pressure                       int64
weather__hourly__cloudcover                     int64
Category                                        int64
dtype: object

In [29]:
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [30]:
categorical_cols = [
    'Airline',
    'From',
    'To',
    'Status',
    'Category',
    'weather__hourly__weatherDesc__value'
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [31]:
df.isnull().sum()

Used Date                               0
From                                    0
To                                      0
Airline                                 0
Scheduled Departure                     0
SDEP                                    0
Departure                               0
DEP                                    74
Scheduled Arrival                       0
SARR                                    0
Arrival                                 0
ARR                                    74
Departure Delay                         0
Arrival Delay                           0
Status                                  0
Distance                                0
Passenger Load Factor                   0
Airline Rating                          0
Airport Rating                          0
Market Share                            0
OTP Index                               0
weather__hourly__windspeedKmph          0
weather__hourly__weatherDesc__value     0
weather__hourly__precipMM               0
weather__hourly__humidity               0
weather__hourly__visibility             0
weather__hourly__pressure               0
weather__hourly__cloudcover             0
Category                                0
dtype: int64

In [32]:
df[['DEP', 'ARR']].dtypes

DEP    float64
ARR    float64
dtype: object

In [33]:
df[['DEP', 'ARR']] = df[['DEP', 'ARR']].fillna(df[['DEP', 'ARR']].median())

In [34]:
df.isnull().sum()

Used Date                              0
From                                   0
To                                     0
Airline                                0
Scheduled Departure                    0
SDEP                                   0
Departure                              0
DEP                                    0
Scheduled Arrival                      0
SARR                                   0
Arrival                                0
ARR                                    0
Departure Delay                        0
Arrival Delay                          0
Status                                 0
Distance                               0
Passenger Load Factor                  0
Airline Rating                         0
Airport Rating                         0
Market Share                           0
OTP Index                              0
weather__hourly__windspeedKmph         0
weather__hourly__weatherDesc__value    0
weather__hourly__precipMM              0
weather__hourly__humidity              0
weather__hourly__visibility            0
weather__hourly__pressure              0
weather__hourly__cloudcover            0
Category                               0
dtype: int64

In [40]:
(df == -1).sum().sum()

np.int64(0)

In [42]:
df.replace("-1", np.nan, inplace=True)

In [43]:
df.replace(-1, np.nan, inplace=True)

In [44]:
(df == -1).sum().sum()

np.int64(0)

In [45]:
(df == "-1").sum().sum()

np.int64(0)

In [47]:
df.to_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\flight-delay-intelligence\\data\\cleaned\\cleaned_flights.csv", index=False)