In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\sanch\\OneDrive\\Desktop\\flight-delay-intelligence\\data\\cleaned\\cleaned_flights.csv")

In [3]:
df.head()

,Used Date,From,To,Airline,Scheduled Departure,SDEP,Departure,DEP,Scheduled Arrival,SARR,...,Market Share,OTP Index,weather__hourly__windspeedKmph,weather__hourly__weatherDesc__value,weather__hourly__precipMM,weather__hourly__humidity,weather__hourly__visibility,weather__hourly__pressure,weather__hourly__cloudcover,Category
0,2020-01-31,DEL,HYD,Air Asia,6:05,605,6:04,604.0,8:15,815,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,0
1,2020-01-31,DEL,HYD,Indigo,4:50,450,4:36,436.0,7:00,700,...,47.5,81.1,11,Partly cloudy,0,90,9,1012,57,0
2,2020-01-30,DEL,HYD,Air Asia,6:05,605,5:54,554.0,8:15,815,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,0
3,2020-01-30,DEL,HYD,Air Asia,17:40,1740,17:40,1740.0,19:55,1955,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,0
4,2020-01-30,DEL,HYD,Air Asia,19:50,1950,19:54,1954.0,22:10,2210,...,5.3,85.6,11,Partly cloudy,0,90,9,1012,57,1

In [4]:
df["Used Date"] = pd.to_datetime(df["Used Date"])

#### Month Feature

In [5]:
df["Month"] = df["Used Date"].dt.month

In [6]:
df[["Used Date", "Month"]].head()

   Used Date  Month
0 2020-01-31      1
1 2020-01-31      1
2 2020-01-30      1
3 2020-01-30      1
4 2020-01-30      1

#### Day Feature

In [7]:
df["Day"] = df["Used Date"].dt.day

In [8]:
df[["Used Date", "Day"]].head()

   Used Date  Day
0 2020-01-31   31
1 2020-01-31   31
2 2020-01-30   30
3 2020-01-30   30
4 2020-01-30   30

#### Weekday Feature

In [9]:
df["Weekday"] = df["Used Date"].dt.day_name()

In [10]:
df[["Used Date", "Weekday"]].head()

   Used Date   Weekday
0 2020-01-31    Friday
1 2020-01-31    Friday
2 2020-01-30  Thursday
3 2020-01-30  Thursday
4 2020-01-30  Thursday

#### Total Delay

In [13]:
df["Total Delay"] = (
    df["Departure Delay"] +
    df["Arrival Delay"]
)

In [14]:
df[[
    "Departure Delay",
    "Arrival Delay",
    "Total Delay"
]].head()

   Departure Delay  Arrival Delay  Total Delay
0              1.0            1.0          2.0
1            -14.0           -5.0        -19.0
2            -11.0          -13.0        -24.0
3              0.0          -13.0        -13.0
4              4.0            4.0          8.0

#### Delay Category

In [19]:
def delay_category(delay):

    if delay == 0:
        return "On Time"

    elif delay <= 10:
        return "Minor Delay"

    elif delay <= 60:
        return "Moderate Delay"

    else:
        return "Severe Delay"

In [20]:
df["Delay Category"] = df["Total Delay"].apply(
    delay_category
)

In [21]:
df[[
    "Total Delay",
    "Delay Category"
]].head()

   Total Delay Delay Category
0          2.0    Minor Delay
1        -19.0    Minor Delay
2        -24.0    Minor Delay
3        -13.0    Minor Delay
4          8.0    Minor Delay

#### Route Feature

In [22]:
df["Route"] = (
    df["From"] +
    "-" +
    df["To"]
)

In [23]:
df[[
    "From",
    "To",
    "Route"
]].head()

  From   To    Route
0  DEL  HYD  DEL-HYD
1  DEL  HYD  DEL-HYD
2  DEL  HYD  DEL-HYD
3  DEL  HYD  DEL-HYD
4  DEL  HYD  DEL-HYD

#### Peak Hour Feature

In [24]:
def peak_hour(dep):

    dep = int(dep)

    if 600 <= dep <= 1000:
        return "Morning Peak"

    elif 1700 <= dep <= 2100:
        return "Evening Peak"

    else:
        return "Off Peak"

In [25]:
df["Peak Hour"] = df["SDEP"].apply(
    peak_hour
)

In [26]:
df[[
    "SDEP",
    "Peak Hour"
]].head()

   SDEP     Peak Hour
0   605  Morning Peak
1   450      Off Peak
2   605  Morning Peak
3  1740  Evening Peak
4  1950  Evening Peak

#### Weather Severity Score

In [27]:
df["Weather Severity"] = (
    df["weather__hourly__windspeedKmph"] * 0.3
    +
    df["weather__hourly__humidity"] * 0.2
    +
    df["weather__hourly__precipMM"] * 0.5
)

In [28]:
df[[
    "weather__hourly__windspeedKmph",
    "weather__hourly__humidity",
    "weather__hourly__precipMM",
    "Weather Severity"
]].head()

,weather__hourly__windspeedKmph,weather__hourly__humidity,weather__hourly__precipMM,Weather Severity
0,11,90,0,21.3
1,11,90,0,21.3
2,11,90,0,21.3
3,11,90,0,21.3
4,11,90,0,21.3

In [ ]:
df.to_csv(
    "C:\\Users\\sanch\\OneDrive\\Desktop\\flight-delay-intelligence\\data\\cleaned\\featured_flights.csv",
    index=False
)